apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: 5demo
spec:
  image: us.gcr.io/container-suite/crunchy-postgres-ha:centos8-13.4-ci-latest
  openshift: true
  port: 5432
  postgresVersion: 13
  instances:
    - name: 'pgc'
      replicas: 3
      resources:
        limits:
          cpu: 1.0
          memory: 2Gi
      volumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi

  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_parallel_workers: 2
          max_worker_processes: 2
          shared_buffers: 256MB
          work_mem: 2MB

  archive:
    pgbackrest:
      image: us.gcr.io/container-suite/crunchy-pgbackrest:centos8-13.4-ci-latest
      repoHost:
        dedicated: {}
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            storageClassName: "standard"
            resources:
              requests:
                storage: 10Gi

